[build]
  base = "/"
  command = "npm ci && npm run build"
  publish = "/dist"
  environment = {
    NODE_VERSION = "18"
    NODE_ENV = "production"
    VITE_ENV = "production"
    VITE_BASE = "/"
  }

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_ENV = "production"
  VITE_BASE = "/"
