[build]
  base = "/"
  command = "npm install && npm ci && npm run build"
  publish = "/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_ENV = "production"
  VITE_BASE = "/"

[build]
  command = "npm ci && npm run build"
